#ifndef N64_TYPES_H
#define N64_TYPES_H

#ifndef _LANGUAGE_C
#define _LANGUAGE_C
#endif

#define _ULTRATYPES_H_

#include <stdint.h>
#include <stddef.h>
#include <math.h> 

typedef uint8_t   u8;
typedef uint16_t  u16;
typedef uint32_t  u32;
typedef uint64_t  u64;
typedef int8_t    s8;
typedef int16_t   s16;
typedef int32_t   s32;
typedef int64_t   s64;
typedef float     f32;
typedef double    f64;

typedef s32       n64_bool;

#ifndef TRUE
#define TRUE 1
#endif

#ifndef FALSE
#define FALSE 0
#endif

#ifdef __cplusplus
extern "C" {
#endif

#include <ultra64.h> 
#include <PR/sched.h>

// --- ADDED: The Global State Structure ---
typedef struct {
    // This is the pointer to the raw pixels generated by the N64
    // Usually 320x240 * 4 bytes (RGBA)
    uint32_t* screenBuffer; 
    
    // You can add other global states here (audio buffers, etc.)
    uint32_t frameCount;
} ALGlobals;

#ifdef __cplusplus
}
#endif

#undef NULL
#define NULL 0

#endif // N64_TYPES_H
